### ISSUE TITLE
BrAPI support

### ISSUE THREAD

**Issue by lukasmueller** [IPK-BIT/divbrowse#2]
Is BrAPI support already available?

**Comment by patrick-koenig** [comment]
Dear Lukas,

BrAPI support is currently not an official feature of the latest release of DivBrowse. We are currently in the process of manuscript revision and therefore have introduced a "release freeze" for DivBrowse development.

We have started the implementation of BrAPI support for /allelematrix call for the DivBrowse server component during the last BrAPI Virtual Hackathon but some minor parts are still missing (e.g. configuration).

Our plan is to finalize BrAPI support for the server component by March 2023 and then directly start implementing BrAPI support for the client component (GUI) of DivBrowse.

Wish you a merry christmas!
Patrick
